#!/bin/bash
# PackageList1='quilt dh-make dh-systemd build-essential devscripts lintian perl gawk dkms'
PackageList1='quilt net-tools'
for Package in $PackageList1
do
	function CheckPackageExists {
		dpkg -l "$Package"  | grep "$Package" | wc -l
	}
	PackageExists=$(CheckPackageExists)
	if [ $PackageExists -eq 0 ]
	then
		sudo apt-get install $i
	fi
done
